site_name: MuSTDrifter

# use_directory_urls: false

theme:
  name: material
  logo: assets/logo.svg

site_url: https://oeg-upm.github.io/mustdrifter/
repo_url: https://github.com/oeg-upm/mustdrifter
repo_name: oeg-upm/mustdrifter

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
            - mustdrifter.drift
            - mustdrifter.report
          options:
            members_order: source
            show_source: false
            inherited_members: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            docstring_style: numpy

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - MuSTDrifter: mustdrifter.md
  - API:
    - Preprocessing: preprocessing.md
    - Drift: drift.md
    - Report: report.md
