
from .pos_annotation import annotate_pos

from .pos_distributions import get_lexical_distribution
from .pos_distributions import get_syntactic_content_distribution, get_syntactic_style_distribution, get_syntactic_style_sub_distributions

from .topic_distributions import get_thematic_dimension
